import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/custom-components/SideBar";
// import TopBar from "@/custom-components/TopBar";
import { Menu, MenuIcon } from "lucide-react";
import { ReactNode } from "react";
import TopBar from "@/custom-components/TopBar/TopBar";
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Togdheergym",
  description: "Generated by create next app",
};
interface MenuIcon {
  icon: ReactNode;
}

const menu: MenuIcon = {
  icon: <Menu />,
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#e5f4fb]">
      {/* <SideBar /> */}
      <body>
        <TopBar />
        {children}
      </body>
    </html>
  );
}
