import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/custom-components/SideBar";
// import TopBar from "@/custom-components/TopBar";
import { Menu, MenuIcon } from "lucide-react";
import { ReactNode } from "react";
import TopBar from "@/custom-components/TopBar/TopBar";
import Tutorial from "@/custom-components/Tutorial/Tutorial";
import TopBar2 from "@/custom-components/TopBar2/TopBar2";
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Togdheergym",
  description: "Generated by create next app",
};
interface MenuIcon {
  icon: ReactNode;
}

 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <SideBar /> */}
      <body className="bg-[#e5f4fb]">
        <TopBar2 />
        {/* <Tutorial/> */}
        {children}
      </body>
    </html>
  );
}
