import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import TopBar from "@/custom-components/TopBar";

const roboto = Roboto({ subsets: ["latin"] ,weight:'400'});

export const metadata: Metadata = {
  title: "Togdheergym",
  description: "Generated by create next app",
  // icons:['./transparent_logo.png']
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-100">
      <body >
        <TopBar/>
         {children}
      </body>
    </html>
  );
}
